SETTING_FILENAME = 'filename'
SETTING_RECENT_FILES = 'recentFiles'
SETTING_WIN_SIZE = 'window/size'
SETTING_WIN_POSE = 'window/position'
SETTING_WIN_GEOMETRY = 'window/geometry'
SETTING_LINE_COLOR = 'line/color'
SETTING_FILL_COLOR = 'fill/color'
SETTING_ADVANCE_MODE = 'advanced'
SETTING_WIN_STATE = 'window/state'
SETTING_SAVE_DIR = 'savedir'
SETTING_PAINT_LABEL = 'paintlabel'
SETTING_LAST_OPEN_DIR = 'lastOpenDir'
SETTING_AUTO_SAVE = 'autosave'
SETTING_AUTO_SAVE_ENABLED = 'autoSaveEnabled'  # Timer-based auto-save toggle
SETTING_AUTO_SAVE_INTERVAL = 'autoSaveInterval'  # Interval in seconds
SETTING_SINGLE_CLASS = 'singleclass'
FORMAT_PASCALVOC='PascalVOC'
FORMAT_YOLO='YOLO'
FORMAT_CREATEML='CreateML'
FORMAT_COCO = 'COCO'
FORMAT_YOLO_SEG = 'YOLO_SEG'
SETTING_DRAW_SQUARE = 'draw/square'
SETTING_LABEL_FILE_FORMAT= 'labelFileFormat'
SETTING_FILE_VIEW_MODE = 'fileViewMode'
SETTING_GALLERY_MODE = 'galleryMode'
SETTING_ICON_SIZE = 'iconSize'
SETTING_TOOLBAR_EXPANDED = 'toolbarExpanded'
SETTING_DARK_MODE = 'darkMode'
SETTING_LOCK_ON_VERIFY = 'lockOnVerify'
SETTING_GRID_ENABLED = 'gridEnabled'
SETTING_GRID_SIZE = 'gridSize'
SETTING_EDGE_ALIGNMENT = 'edgeAlignment'
SETTING_SHORTCUTS = 'shortcuts'
DEFAULT_ENCODING = 'utf-8'
# SAM-assisted polygon settings
SETTING_SAM_ENCODER = 'sam/encoderPath'     # encoder .onnx; '' = bundled default
SETTING_SAM_DECODER = 'sam/decoderPath'     # decoder .onnx; '' = bundled default
